apiVersion: v1
kind: Service
metadata:
  name: book-service-demo
spec:
  type: NodePort
  selector:
    app: book-service-demo
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30081