apiVersion: v1
kind: Service
metadata:
  name: bookservice
  namespace: bookservice
spec:
  selector:
    app: bookservice
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP