apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: bookservice
spec:
  selector:
    app: gateway
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP